### ISSUE TITLE
Luster Naming

### ISSUE THREAD

**Issue by nsmryan** [kyren/piccolo#26]
I just published a crate named luster, not realizing that there was a Rust program of that name.
I dont mind trying to change my crate if you might still want the name 'luster'.

Just let me know!

**Comment by kyren** [comment]
WELL, I thought this project was dead, so I didn't think this was a big issue....

It's been several years, maybe *I* should be the one to rename now?

**Comment by ildar** [comment]
+1, the name is very unsuitable.

**Comment by kyren** [comment]
WELL I renamed the project to something that *absolutely nobody* could EVER find tasteless and dumb. Also something that is not currently taken on crates.io

**Comment by ildar** [comment]
`luster` /ˈlʌstə/ doesn't sound like Lua /lu:ʌ/ so no direct association.
And, yes, associations are very subjective. Yet e.g. my 1st association is:
`cluster` which is misleading.

**Comment by ildar** [comment]
+1 for the new name.

**Comment by kyren** [comment]
> `luster` /ˈlʌstə/ doesn't sound like Lua /lu:ʌ/ so no direct association.
> And, yes, associations are very subjective. Yet e.g. my 1st association is:
> `cluster` which is misleading.

Fair enough, makes sense! Thanks for the feedback!

> +1 for the new name.

I picked it also because it sounds like "pico-lua"

**Comment by kyren** [comment]
aaaaAAAAAA there's already a rust language project called 'piccolo' that's not on crates.io

https://github.com/zphixon/piccolo

I checked for an existing project by searching on crates.io, then *reserved* the name like a jerk.

Now I guess I have to pick a new name AND give the owner of that repo control over the crate name somehow

**Comment by Veykril** [comment]
Why not go with `piccolua` then

**Comment by manokara** [comment]
How about `luar`? It's kind of `rlua` backwards, can be read like "lua (for) rust", means moonlight in Portuguese and is available on crates.io!

**Comment by kyren** [comment]
Nope, it's now named deimos, because it's the smallest of the solar system's moons that I could think of off of the top of my head, it sounds cool, and it isn't taken by anything that this would be confused with or anything on crates.io.

**Comment by kyren** [comment]
OKAY, I have gotten permission from zphixon to keep the name 'piccolo' (thank you!), and I have decided I like that name more.

I am truly sorry for renaming this project 3 times in the span of less than a week.

I promise I'm done.

**Comment by XVilka** [comment]
Probably could be unpinned now.
