### ISSUE TITLE
[BUG] Examples do not compile

### ISSUE THREAD

**Issue by Dzordzu** [kyren/piccolo#31]
## Problem
Self descriptive

## Versions
Rust: 1.72
Piccolo: Both 0.1.0 and 0.1.1

### Iterpreter example 
Changes in API. No `reset` method for `Thread` and more

### Compiled example
The trait bounds are not satisfied

**Comment by kyren** [comment]
I believe that is because of the disconnect between cargo and the WIP version on github?

**Comment by kyren** [comment]
This is also partially my fault for not tagging the last release so that it would be easy to see that release in github. I'll close this when I release a new version on crates.io and properly tag it.

**Comment by Dzordzu** [comment]
Great. Thanks a lot!
