### ISSUE TITLE
Small detail about JS Functions in your post.

### ISSUE THREAD

**Issue by ShawSumma** [kyren/piccolo#61]
In your post you do something that looks like ```
(() => {
  /* code here */
}).bind(this)```

This is good code but this is already bound.

JavaScript arrow functions are different to `function` functions in that they bind this in their closure.

It would help my JS brain if this was fixed. Thanks!

**Comment by kyren** [comment]
Thanks, fixed!

I'm not terribly experienced with javascript, so I didn't actually know that, thank you for telling me!
