### ISSUE TITLE
question: are async calls into the vm Send?

### ISSUE THREAD

**Issue by wez** [kyren/piccolo#62]
I'm using [mlua](https://docs.rs/mlua/latest/mlua/) quite heavily in a couple of applications.
One pain point that I have in one of them is that that futures that result from async calls into the VM are `!Send`, making it rather awkward to integrate in the regular multi threaded tokio runtime.

Is piccolo different?

Also: one thing I love about mlua is how easy it is to define custom embedded modules and types and map them into lua.
How's that look in piccolo? I'm happy to read code examples, but I didn't spot anything obviously like that on a very very quick glance.  Can you point me to stuff to look at?

Thanks! This project sounds very interesting to me!

**Comment by khvzak** [comment]
Just to note, next `mlua` version will have `send` feature flag replaced with `sync` to easily work with multithreaded apps. Under the hood it will use ReentrantMutex to support multi lock within a single thread.

**Comment by kyren** [comment]
> Also: one thing I love about mlua is how easy it is to define custom embedded modules and types and map them into lua.
How's that look in piccolo? I'm happy to read code examples, but I didn't spot anything obviously like that on a very very quick glance. Can you point me to stuff to look at?

There's not much to look at, this project is still in its early stages. Usually most things *work* but they're not *easy*. You can check out [the util crate](https://github.com/kyren/piccolo/tree/master/util) and the [Static]UserMethods helpers: https://github.com/kyren/piccolo/blob/master/util/src/user_methods.rs if you want to see an example.

**Comment by kyren** [comment]
This issue made me think about it again, and I'm going to look with fresh eyes on a way to make `gc-arena` conditionally `Send` in a different way than https://github.com/kyren/gc-arena/pull/61, because being able to make `Lua` `Send` is also very important to me.

**Comment by kyren** [comment]
I believe there is a path forward with `gc-arena` towards safe "send jails" that can reasonably make the piccolo VM send.

I'm going to close this issue though because the discussion of mlua is unrelated.
